// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uunoEEDogHzkMXiHpEbU64
// Component: 78646OHncnd3
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant,
  useCurrentUser
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Navbar from "../../Navbar"; // plasmic-import: ddKbSYWJnNzJ/component
import Button from "../../Button"; // plasmic-import: 6aP2U4alYtJI/component
import Section from "../../Section"; // plasmic-import: -m4d9JXCb8vj/component
import DiagramCard from "../../DiagramCard"; // plasmic-import: qDnztiEl37q6/component
import ProductCard from "../../ProductCard"; // plasmic-import: b6046LC5jlXm/component
import DetailAbout from "../../DetailAbout"; // plasmic-import: CkP7MMho2GgB/component
import PriceSection from "../../PriceSection"; // plasmic-import: 1at-Qzm3VKS4/component
import PriceCard from "../../PriceCard"; // plasmic-import: V4ecTuxcF7vu/component
import FooterSection from "../../FooterSection"; // plasmic-import: STpLo0aBQ-DK/component
import { useScreenVariants as useScreenVariantsh25UAOp1AQ6B } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: H25uAOp1aQ6b/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic.module.css"; // plasmic-import: uunoEEDogHzkMXiHpEbU64/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: 78646OHncnd3/css
import IconArrowRightsvgIcon from "./icons/PlasmicIcon__IconArrowRightsvg"; // plasmic-import: -_TM0Q1qL5qg/icon
import diagramsvgUwptPryRrvOt from "./images/diagramsvg.svg"; // plasmic-import: uwptPryRRVOt/picture
import logoHero1PngBP38KdA2Psf from "./images/logoHero1Png.png"; // plasmic-import: bP38KdA2Psf-/picture
import logoHero2PngWj5X0EYdokF from "./images/logoHero2Png.png"; // plasmic-import: wj5x0eYdokF_/picture
import logoHero3PngMqbKeOuVsIv from "./images/logoHero3Png.png"; // plasmic-import: MqbKEOuVS_iv/picture
import logoHero4Png80TT5Cj5PCt from "./images/logoHero4Png.png"; // plasmic-import: 80tT5Cj5_pCt/picture
import diagramImgsvgJW9Rj1VFxBc from "./images/diagramImgsvg.svg"; // plasmic-import: J-W9RJ1VFxBc/picture
import ellipseLeftpngI1TOrwIUmDg from "./images/ellipseLeftpng.png"; // plasmic-import: i1tOrw-iUMDg/picture
import ellipseRightpngTgeRvELb66Ny from "./images/ellipseRightpng.png"; // plasmic-import: tgeRvELb66ny/picture
import terminalpngEDpdXabOx386 from "./images/terminalpng.png"; // plasmic-import: eDpdXabOx386/picture
import line1PngCc7ZArUEhJ8L from "./images/line1Png.png"; // plasmic-import: Cc7zArUEhJ8L/picture
import lineBranchpngEcXlj66HIaIs from "./images/lineBranchpng.png"; // plasmic-import: ecXlj66hIaIs/picture
import line2PngUxpiaTzPsJpe from "./images/line2Png.png"; // plasmic-import: UXPIATzPsJPE/picture
import dollarpngHkHvKxZ4CNt from "./images/dollarpng.png"; // plasmic-import: HkHVKxZ4cNt_/picture
import messagepngAq4L7DCs5J0K from "./images/messagepng.png"; // plasmic-import: Aq4L7DCs5J0k/picture
import importpngByS8Ua5TuV6P from "./images/importpng.png"; // plasmic-import: byS8Ua5tuV6P/picture
import exportpngFQcfRvjtzunR from "./images/exportpng.png"; // plasmic-import: fQcfRvjtzunR/picture
import message2Png5T6E7OqusBo from "./images/message2Png.png"; // plasmic-import: 5t6-e7OqusBO/picture
import message3PngQgLspwL4ZJLt from "./images/message3Png.png"; // plasmic-import: QGLspwL4zJLt/picture
import macbookpngZhpePWsPWqRq from "./images/macbookpng.png"; // plasmic-import: ZhpePWsPWqRQ/picture
import galleri11PngZKMpmgQTohg from "./images/galleri11Png.png"; // plasmic-import: zK_MpmgQTohg/picture
import galleri12PngYEyrfwEmLoz7 from "./images/galleri12Png.png"; // plasmic-import: YEyrfwEmLOZ7/picture
import galleri13PngCUp0SIqO5AyU from "./images/galleri13Png.png"; // plasmic-import: cUp0sIqO5ayU/picture
import galleri21Png1ZiYgVDgW0L from "./images/galleri21Png.png"; // plasmic-import: 1ZiYg-VDgW0L/picture
import galleri22PngSt6BTnJfSsJw from "./images/galleri22Png.png"; // plasmic-import: ST6bTNJfSsJw/picture
import galleri23Png3HVeoqnCmAs from "./images/galleri23Png.png"; // plasmic-import: 3hVEOQNCmAS-/picture
import aboutImgpngFpekixow7ZjL from "./images/aboutImgpng.png"; // plasmic-import: fpekixow7ZjL/picture
import aboutIpsumpngCC6CEtNdVvor from "./images/aboutIpsumpng.png"; // plasmic-import: cC6cEtNdVvor/picture
import backtippngXLifrvEgWHh from "./images/backtippng.png"; // plasmic-import: xLIFRV_egWHh/picture
import arrowLeftpngNtRuW3OsLl89 from "./images/arrowLeftpng.png"; // plasmic-import: ntRuW3OSLl89/picture
import arrowRightpng2ECoA7JqHd4BQ from "./images/arrowRightpng2.png"; // plasmic-import: ECoA7jqHd4bQ/picture
import pricingImgsvgBh8TEnR8NWz9 from "./images/pricingImgsvg.svg"; // plasmic-import: BH8tEnR8nWZ9/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicHomepage.pageMetadata.title}
      />

      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicHomepage.pageMetadata.title}
      />
    </>
  );
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsh25UAOp1AQ6B()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__e1Z5)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vcQtf)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ns1DX)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Analytics for developers can be better"
                      : "Analytics for \ndevelopers can\nbe better"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nyw3H
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                      : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1PxQ5)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__fVopj
                      )}
                      color={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "blueSmall"
                          : "blue"
                      }
                      endIcon={
                        <IconArrowRightsvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___9EoQb
                          )}
                          role={"img"}
                        />
                      }
                      link={"#"}
                      showEndIcon={true}
                      startIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__pkkRg)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lEG
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Try Demo For Free"
                          : "Try Demo For Free"}
                      </div>
                    </Button>
                    <Button
                      className={classNames("__wab_instance", sty.button__vJqS)}
                      color={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "blueBorderSmall"
                          : "blueBorder"
                      }
                      endIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__q0Pkn)}
                          role={"img"}
                        />
                      }
                      link={"#"}
                      startIcon={
                        <svg
                          className={classNames(projectcss.all, sty.svg__taNcD)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zf3FI
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Learn More"
                          : "Learn More"}
                      </div>
                    </Button>
                  </Stack__>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___32MRd
                      )}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__sJrfP
                        )}
                        color={"blueBorder"}
                        endIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__eBz6I
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__uawdg
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        {"Learn More"}
                      </Button>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___4Eoe
                        )}
                        color={"blueBorder"}
                        endIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg___8YlFr
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <svg
                            className={classNames(
                              projectcss.all,
                              sty.svg__iBpdT
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        {"Learn More"}
                      </Button>
                    </div>
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qHiyc)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hdHtV)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "0px"
                        : "661px"
                    }
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: diagramsvgUwptPryRrvOt,
                      fullWidth: 173,
                      fullHeight: 150,
                      aspectRatio: 1.151631
                    }}
                  />
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j2YX
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Powering with magnificant of Companies"
                  : "Powering with magnificant of Companies"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sqOcm)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__gfjYt)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero1PngBP38KdA2Psf,
                    fullWidth: 233,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qmHl)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero2PngWj5X0EYdokF,
                    fullWidth: 189,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__x9OxE)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero3PngMqbKeOuVsIv,
                    fullWidth: 194,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___9CDgn)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "170px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: logoHero4Png80TT5Cj5PCt,
                    fullWidth: 189,
                    fullHeight: 50,
                    aspectRatio: undefined
                  }}
                />
              </Stack__>
            </div>
          </Stack__>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___9Lo0)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: diagramImgsvgJW9Rj1VFxBc,
              fullWidth: 300,
              fullHeight: 100,
              aspectRatio: 2.987552
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__nyWpF)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"774px"}
            loading={"lazy"}
            src={{
              src: ellipseLeftpngI1TOrwIUmDg,
              fullWidth: 469,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__elOMi)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: ellipseRightpngTgeRvELb66Ny,
              fullWidth: 437,
              fullHeight: 742,
              aspectRatio: undefined
            }}
          />

          <Section
            data-plasmic-name={"diagramSection"}
            data-plasmic-override={overrides.diagramSection}
            className={classNames("__wab_instance", sty.diagramSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__llBsV)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__swwwU
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor \nsit amet"
                  : "Lorem ipsum dolor \nsit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xYzyS
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___7Av1)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "249px"
                    : "100%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: terminalpngEDpdXabOx386,
                  fullWidth: 624,
                  fullHeight: 333,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ddGjw)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: line1PngCc7ZArUEhJ8L,
                  fullWidth: 11,
                  fullHeight: 150,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__es3Mi)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "50px"
                    : "100%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: lineBranchpngEcXlj66HIaIs,
                  fullWidth: 100,
                  fullHeight: 100,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___7Sk5R)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "500px"
                    : "770px"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "auto"
                    : "auto"
                }
                loading={"lazy"}
                src={{
                  src: line2PngUxpiaTzPsJpe,
                  fullWidth: 844,
                  fullHeight: 284,
                  aspectRatio: undefined
                }}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jdOf5)}
              >
                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__aeRf
                  )}
                />

                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__x8B7
                  )}
                />

                <DiagramCard
                  className={classNames(
                    "__wab_instance",
                    sty.diagramCard__on0C
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lztRw)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ewMnx)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: dollarpngHkHvKxZ4CNt,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ixNez)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: messagepngAq4L7DCs5J0K,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ttbzV)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: importpngByS8Ua5TuV6P,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___9WOm)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: lineBranchpngEcXlj66HIaIs,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rwC8M)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: exportpngFQcfRvjtzunR,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___6IgYl)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: message2Png5T6E7OqusBo,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__avi4R)}
                  displayHeight={"auto"}
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "72px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: message3PngQgLspwL4ZJLt,
                    fullWidth: 100,
                    fullHeight: 100,
                    aspectRatio: undefined
                  }}
                />
              </Stack__>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ihkq4
                )}
              >
                {"Lorem ipsum dolor \nsit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__floJe
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                }
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"deviceSection"}
            data-plasmic-override={overrides.deviceSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.deviceSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__iV65U)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__tu6Rq
                )}
              >
                {"Lorem ipsum dolor sit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iA9Dg
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."}
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__okChY)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "360px"
                  : "100%"
              }
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: macbookpngZhpePWsPWqRq,
                fullWidth: 900,
                fullHeight: 565,
                aspectRatio: undefined
              }}
            />
          </Section>
          <Section
            data-plasmic-name={"gallerySection"}
            data-plasmic-override={overrides.gallerySection}
            className={classNames("__wab_instance", sty.gallerySection)}
            size={"fullContentGallery"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__aigb0)}>
              <div className={classNames(projectcss.all, sty.columns__lr9Lm)}>
                <div className={classNames(projectcss.all, sty.column__oLvm)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fw3F)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri11PngZKMpmgQTohg,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__wtOg)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jFr9L)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri12PngYEyrfwEmLoz7,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__u6Jfr)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__drDtF)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri13PngCUp0SIqO5AyU,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.columns__lQtWa)}>
                <div className={classNames(projectcss.all, sty.column__r0Etp)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fgU)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri21Png1ZiYgVDgW0L,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__f8J9G)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iLeS)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri22PngSt6BTnJfSsJw,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__avzCa)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kioHh)}
                    displayHeight={"100%"}
                    displayMaxHeight={"300px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: galleri23Png3HVeoqnCmAs,
                      fullWidth: 700,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"productSection"}
            data-plasmic-override={overrides.productSection}
            className={classNames("__wab_instance", sty.productSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__evWwb)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__e3Tel
                )}
              >
                {"Lorem ipsum dolor sit amet"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gU11
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do \neiusmod tempor incididunt ut labore et dolore magna aliqua."
                }
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__ftqZc)}
                color={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "blue"
                    : "blue"
                }
                endIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg___4WVdL)}
                    role={"img"}
                  />
                }
                link={"#"}
                startIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg__joE9X)}
                    role={"img"}
                  />
                }
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Flgk
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "Get Started"
                    : "Get Started"}
                </div>
              </Button>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uYiC)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qu77Z
                  )}
                />

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fJnvx
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__liILf)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yl3Yo
                  )}
                />

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iimr5
                  )}
                />
              </Stack__>
            </div>
          </Section>
          <Section
            data-plasmic-name={"aboutSection"}
            data-plasmic-override={overrides.aboutSection}
            background={"dark"}
            className={classNames("__wab_instance", sty.aboutSection)}
            size={
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? "mobile"
                : undefined
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__zgGwa)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dzw6Q
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "What people say \nabout us"
                  : "What people say about us"}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox__tWd6M)}>
                <div className={classNames(projectcss.all, sty.freeBox__dhuYp)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6Rx1I)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "339px"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: aboutImgpngFpekixow7ZjL,
                      fullWidth: 400,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fRxU)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__bdGzG
                    )}
                  >
                    {"Michael Justin"}
                  </h2>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sxH6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___83QbG)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: aboutIpsumpngCC6CEtNdVvor,
                        fullWidth: 152,
                        fullHeight: 40,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x3BNw
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "CEO Company"
                        : "CEO Company"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mJ4L6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jF1Ml)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "auto"
                          : "auto"
                      }
                      loading={"lazy"}
                      src={{
                        src: backtippngXLifrvEgWHh,
                        fullWidth: 34,
                        fullHeight: 32,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b9JNk
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                      : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
                  </div>
                </div>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___29Xaf)}
              >
                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__bmuAs
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__iwBc7
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__eezEw
                  )}
                />
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jjy3G)}
              >
                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__vMRfk
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout__mvFla
                  )}
                />

                <DetailAbout
                  className={classNames(
                    "__wab_instance",
                    sty.detailAbout___2EFjp
                  )}
                />
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__trxl9)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: arrowLeftpngNtRuW3OsLl89,
                  fullWidth: 24,
                  fullHeight: 24,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__hbm6E)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: arrowRightpng2ECoA7JqHd4BQ,
                  fullWidth: 24,
                  fullHeight: 24,
                  aspectRatio: undefined
                }}
              />
            </div>
          </Section>
          <PriceSection
            data-plasmic-name={"priceSection"}
            data-plasmic-override={overrides.priceSection}
            className={classNames("__wab_instance", sty.priceSection)}
          />

          <Section
            data-plasmic-name={"startSection"}
            data-plasmic-override={overrides.startSection}
            className={classNames("__wab_instance", sty.startSection)}
            size={"fullContentWidth"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___78UhW)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ofPBj)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: pricingImgsvgBh8TEnR8NWz9,
                  fullWidth: 300,
                  fullHeight: 67,
                  aspectRatio: 4.468401
                }}
              />

              <div className={classNames(projectcss.all, sty.columns__yli4K)}>
                <div className={classNames(projectcss.all, sty.column__vCgP)}>
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Start using our product today"
                      : "Start using our product today"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wEtTm
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."
                      : "Faster than free analytics tools. Access to all your data, with respect to the privacy of your users."}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__j0GfM)}>
                  <Button
                    className={classNames("__wab_instance", sty.button__kEgu6)}
                    color={"white"}
                    endIcon={
                      <svg
                        className={classNames(projectcss.all, sty.svg__gZvUt)}
                        role={"img"}
                      />
                    }
                    link={"#"}
                    startIcon={
                      <svg
                        className={classNames(projectcss.all, sty.svg__wbc93)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fosLq
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Get Started"
                        : "Get Started"}
                    </div>
                  </Button>
                </div>
              </div>
            </div>
          </Section>
          <Section
            data-plasmic-name={"pricingSection"}
            data-plasmic-override={overrides.pricingSection}
            className={classNames("__wab_instance", sty.pricingSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__lUcfj)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___6Nbfu)}
              >
                <div className={classNames(projectcss.all, sty.column__c4YgM)}>
                  <PriceCard
                    borders={["flatLeft"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__lVjBp
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ntAhD)}>
                  <PriceCard
                    borders={["flatCenter"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__xdQbi
                    )}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xhp5F)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dovyj
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "We Recommended"
                        : "We Recommended"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___6NL0M)}>
                  <PriceCard
                    borders={["flatRight"]}
                    className={classNames(
                      "__wab_instance",
                      sty.priceCard__cvr0
                    )}
                  />
                </div>
              </Stack__>
            </div>
          </Section>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "h1",
    "diagramSection",
    "deviceSection",
    "gallerySection",
    "productSection",
    "aboutSection",
    "priceSection",
    "startSection",
    "h3",
    "pricingSection",
    "footerSection"
  ],

  headerHeroSection: ["headerHeroSection", "navbar", "h1"],
  navbar: ["navbar"],
  h1: ["h1"],
  diagramSection: ["diagramSection"],
  deviceSection: ["deviceSection"],
  gallerySection: ["gallerySection"],
  productSection: ["productSection"],
  aboutSection: ["aboutSection"],
  priceSection: ["priceSection"],
  startSection: ["startSection", "h3"],
  h3: ["h3"],
  pricingSection: ["pricingSection"],
  footerSection: ["footerSection"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    h1: makeNodeComponent("h1"),
    diagramSection: makeNodeComponent("diagramSection"),
    deviceSection: makeNodeComponent("deviceSection"),
    gallerySection: makeNodeComponent("gallerySection"),
    productSection: makeNodeComponent("productSection"),
    aboutSection: makeNodeComponent("aboutSection"),
    priceSection: makeNodeComponent("priceSection"),
    startSection: makeNodeComponent("startSection"),
    h3: makeNodeComponent("h3"),
    pricingSection: makeNodeComponent("pricingSection"),
    footerSection: makeNodeComponent("footerSection"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
